### ISSUE TITLE
parsing error with python-3.10

### ISSUE THREAD

**Issue by gagara** [quadrismegistus/cadence#4]
I'm getting following error when trying to use example from readme:
```
>>> sonnet.words()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/slg/projects/poetry/.cadence-venv/lib/python3.10/site-packages/cadence/parsers/docs.py", line 155, in words
    def words(self,para_i=None,**kwargs): return self.get_data(para_i,'words',**kwargs)
  File "/home/slg/projects/poetry/.cadence-venv/lib/python3.10/site-packages/cadence/parsers/docs.py", line 147, in get_data
    odf=func(index=index,**self.kwargs(kwargs))
  File "/home/slg/projects/poetry/.cadence-venv/lib/python3.10/site-packages/cadence/parsers/docs.py", line 222, in words
    return setindex(self._words) if index else resetindex(self._words)
  File "/home/slg/projects/poetry/.cadence-venv/lib/python3.10/site-packages/cadence/tools/tools.py", line 211, in setindex
    df = df[set(df.columns) - set(df.index.names)]
  File "/home/slg/projects/poetry/.cadence-venv/lib/python3.10/site-packages/pandas/core/frame.py", line 3713, in __getitem__
    check_dict_or_set_indexers(key)
  File "/home/slg/projects/poetry/.cadence-venv/lib/python3.10/site-packages/pandas/core/indexing.py", line 2611, in check_dict_or_set_indexers
    raise TypeError(
TypeError: Passing a set as an indexer is not supported. Use a list instead.
```
The same issue with python-3.9
Let me know if you need more info.
Thanks.

**Comment by quadrismegistus** [comment]
Thanks for pointing this out! Does the latest github version work?

```
!pip install -qU git+https://github.com/quadrismegistus/cadence
...
```

?

**Comment by gagara** [comment]
Yes. Works perfectly.
Thanks!

**Comment by jfuruness** [comment]
had the same issue, a new release to pypi would be awesome, but github works well, thank you!
